// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzTmeGXKxAvCobLBGIYMk3qPObTPRcLg0',
    appId: '1:787109348075:web:119483a1271792509174ae',
    messagingSenderId: '787109348075',
    projectId: 'chatapp-a7a38',
    authDomain: 'chatapp-a7a38.firebaseapp.com',
    storageBucket: 'chatapp-a7a38.appspot.com',
    measurementId: 'G-TRPHWWX85N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf0wSNaH97pthUXtsWX2LMPhAIejQ0r4Y',
    appId: '1:787109348075:android:4cb75fa4070cfa9e9174ae',
    messagingSenderId: '787109348075',
    projectId: 'chatapp-a7a38',
    storageBucket: 'chatapp-a7a38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGomZQEClL4gR_Un08U8SzURLgQJ8CC9A',
    appId: '1:787109348075:ios:34afa9ef88922af39174ae',
    messagingSenderId: '787109348075',
    projectId: 'chatapp-a7a38',
    storageBucket: 'chatapp-a7a38.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGomZQEClL4gR_Un08U8SzURLgQJ8CC9A',
    appId: '1:787109348075:ios:a4e662ea29b9f86d9174ae',
    messagingSenderId: '787109348075',
    projectId: 'chatapp-a7a38',
    storageBucket: 'chatapp-a7a38.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
